# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'todo-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todo-app
  
  pod 'Alamofire', '~> 5.5'

  target 'todo-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todo-appUITests' do
    # Pods for testing
  end

end
